<a href="https://colab.research.google.com/github/seyeon0815/Project/blob/main/numpy_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# R install.packages("패키지명")
# 파이썬 라이브러리 설치 코드에서 실행 (x)
# 터미널에서 설치
# 방법 1. conda  설치
# --> 아나콘다 설치 후, conda 설치 (주 사용목적: 데이터 과학)
# conda 라이브러리 관리 (약간 버전 업데이트가 조금 느림)
# 방법 2. pip 설치(개발 + 데이터 과학 + 그외)
# --> 아나콘다 설치 안함/ 파이썬만 설치

#git bash 열고 pip install numpy
# pip install numpy

# Numpy  라이브러리 불러오기

In [ ]:
import numpy as np #(=library dplyr 같은 느낌)
print(np.__version__) #numpy 대신 np로 써도 됨

1.21.5


# 배열로 변한
- 1부터 10까지의 리스트를 만든다.
- Numpy 배열로 변환해서 저장한다.

In [ ]:
temp = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] # 리스트를 바로 쓸 수 없기 때문에 변환을 해 주어야 함
arr = np.array(temp)
print(arr)
print(temp)

[ 1  2  3  4  5  6  7  8  9 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
print(type(temp))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


- arr 배열 숫자 5 출력

In [ ]:
arr[4]
arr[4:8]

array([5, 6, 7, 8])

- Numpy를 사용하여 기초 통계 함수를 사용한다.

In [ ]:
print(np.mean(arr))
np.sum(arr)
np.median(arr)
np.std(arr) #표준편차

5.5


2.8722813232690143

# 사칙연산

In [ ]:
math_scores = [90, 80, 88]
english_scores = [80, 70, 90]

total_scores = math_scores + english_scores #리스트의 합
math_arr = np.array(math_scores)
english_arr = np.array(english_scores)

total_scores = math_arr + english_arr
total_scores

array([170, 150, 178])

In [ ]:
np.min(total_scores)
np.max(total_scores)

178

In [ ]:
math_scores = [90, 80, 88]
english_scores = [80, 70, 90]

total_scores = math_scores + english_scores #리스트의 합
math_arr = np.array(math_scores)
english_arr = np.array(english_scores)

# 사칙연산
print("덧셈:", np.add(math_arr, english_arr))
print("뺄셈:", np.subtract(math_arr, english_arr))
print("곱셈:", np.multiply(math_arr, english_arr))
print("나눗셈:", np.divide(math_arr, english_arr))
print("거듭제곱:", np.power(math_arr, english_arr)) #값이 너무 커서 0으로 나옴, 숫자 변경 시 정상 추출됨

덧셈: [170 150 178]
뺄셈: [10 10 -2]
곱셈: [7200 5600 7920]
나눗셈: [1.125      1.14285714 0.97777778]
거듭제곱: [0 0 0]


# 배열의 생성
- 0차원부터 3차원까지 생성하는 방법
- temp_arr.shape는 axis 축을 기준으로 1차원은 axis=0 (숫자,),
2차원은 axis0(세로), axis1(가로) 순
3차원은 axis0(높이) , axis1(세로), axis2(가로)  ㅣ / ㅡ

In [ ]:
temp_arr = np.array(20)
print(temp_arr)
print(type(temp_arr))
print(temp_arr.shape)

20
<class 'numpy.ndarray'>
()


In [ ]:
# 1차원 배열
temp_arr = np.array([1, 2, 3])
print(temp_arr)
print(type(temp_arr))
print(temp_arr.shape) #3 = 3 * 1 사각형
print(temp_arr.ndim) #차원을 모를 때 확인하는 용

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1


In [ ]:
# 2차원 배열
temp_arr = np.array([[1, 2, 3], [4, 5, 6]]) # 중첩 리스트
print(temp_arr)
print(type(temp_arr))
print(temp_arr.shape) #(2, 3) = 2 * 3
print(temp_arr.ndim) #차원을 모를 때 확인하는 용

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
2


In [ ]:
# 3차원 배열
temp_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(temp_arr)
print(type(temp_arr))
print(temp_arr.shape) # 2*2*3
print(temp_arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
(2, 2, 3)
3


In [ ]:
temp_arr = np.array([1, 2, 3, 4], ndmin = 2) #ndmin을 사용시 2차원 배열로 바뀜
print(temp_arr)
print(type(temp_arr))
print(temp_arr.shape)
print(temp_arr.ndim)

[[1 2 3 4]]
<class 'numpy.ndarray'>
(1, 4)
2


## 소숫점 정렬

In [ ]:
temp_arr = np.trunc([-1.23, 1.23])
temp_arr #cut

array([-1.,  1.])

In [ ]:
temp_arr = np.fix([-1.23, 1.23]) #cut
temp_arr 

array([-1.,  1.])

In [ ]:
temp_arr = np.around([-1.23789, 1.23789], 4) #4 = 표시할 소수점 자리수 입력
temp_arr

array([-1.2379,  1.2379])

In [ ]:
temp_arr = np.floor([-1.23789, 1.23789]) #소숫점 내리기
temp_arr

array([-2.,  1.])

In [ ]:
temp_arr = np.ceil([-1.23789, 1.23789])
temp_arr

array([-1.,  2.])

# 배열을 생성하는 다양한 방법들

In [ ]:
temp_arr = np.arange(5) #반복문 쓸시 사용했던 range
temp_arr

array([0, 1, 2, 3, 4])

In [ ]:
temp_arr = np.arange(1, 11, 3) #1부터 11까지 3칸씩 띄우기
temp_arr #일차함수

array([ 1,  4,  7, 10])

In [ ]:
zero_arr = np.zeros((2, 3))
print(zero_arr)
print(type(zero_arr))
print(zero_arr.shape)
print(zero_arr.ndim)
print(zero_arr.dtype) #64 = 비트 #같은 int여도 bit숫자의 차이가 난다

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
(2, 3)
2
float64


In [ ]:
temp_arr = np.ones((4, 5)) #4*5
print(temp_arr)
print(type(temp_arr))
print(temp_arr.shape)
print(temp_arr.ndim)
print(temp_arr.dtype) # 실수형

temp_arr = np.ones((4, 5), dtype ="int32") #dtype = 데이터 형변환
print(temp_arr)
print(type(temp_arr))
print(temp_arr.shape)
print(temp_arr.ndim)
print(temp_arr.dtype) # 정수형

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>
(4, 5)
2
float64
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
<class 'numpy.ndarray'>
(4, 5)
2
int32


In [ ]:
temp_arr = np.ones((2, 6), dtype ="int32")
temp_res_arr = temp_arr.reshape(3, 4) #res = reshape / 3 * 4 # 2차원으로 바꾸기
print(temp_res_arr)
print(type(temp_res_arr))
print(temp_res_arr.shape)
print(temp_res_arr.ndim)
print(temp_res_arr.dtype) 

temp_arr = np.ones((2, 6), dtype ="int32")
temp_res_arr = temp_arr.reshape(2, 2, 3) #res = reshape / # 3차원으로 바꾸기
print(temp_res_arr)
print(type(temp_res_arr))
print(temp_res_arr.shape)
print(temp_res_arr.ndim)
print(temp_res_arr.dtype) 

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
<class 'numpy.ndarray'>
(3, 4)
2
int32
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
<class 'numpy.ndarray'>
(2, 2, 3)
3
int32


In [ ]:
temp_arr = np.ones((2, 6), dtype ="int32")
temp_res_arr = temp_arr.reshape(5, 3) #error 이유:크기가 12(np.ones 2*6)여야 됨 (1, 12), (2, 6), (3, 4), 그 반대
print(temp_res_arr)
print(type(temp_res_arr))
print(temp_res_arr.shape)
print(temp_res_arr.ndim)
print(temp_res_arr.dtype

SyntaxError: ignored

In [ ]:
temp_arr = np.ones((12, 12), dtype = "int32")
temp_res_arr = temp_arr.reshape(4,-1) #뒤에 어떤 숫자를 넣어야 할 지 모르겠을 때 -1입력시 자동으로 출력(총 값은 12*12=144가 되어야 함)/#(5, -1)은 안됨 144/5 불가
print(temp_res_arr)
print(type(temp_res_arr))
print(temp_res_arr.shape)
print(temp_res_arr.ndim)
print(temp_res_arr.dtype)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
<class 'numpy.ndarray'>
(4, 36)
2
int32


# numpy 조건식

In [ ]:
temp_arr = np.arange(10)
temp_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 5보다 작은 값은 원래값으로 반환
# 5보다 큰 값은 원래값 * 10

np.where(temp_arr < 5, temp_arr, temp_arr * 10) # 5보다 작을시(조건),temp(추출),그 외 경우 *10 (그 외 경우 추출)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [ ]:
#0~100 까지의 배열 만들고, 50보다 작은 값은 곱하기 10, 나머지는 그냥 원래 값으로 반환
temp_arr = np.arange(101) #100이 아닌 101 !0부터 숫자 셈!
np.where(temp_arr < 50, temp_arr * 10, temp_arr)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250,
       260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380,
       390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

- np.select

In [ ]:
temp_arr = np.arange(10)

# 5보다 큰 수 곱하기 2, 2보다 작은 값은 

condlist = [temp_arr > 5, temp_arr <2] #조건이 두 개 일 때 np.where (x), np.select (o)
choicelist = [temp_arr * 2, temp_arr +100]
np.select(condlist, choielist) #np.select(codlist,choicelist,default=0) 숫자 지정 안하면 0값으로 나옴

condlist = [temp_arr > 5, temp_arr <2] 
choicelist = [temp_arr * 2, temp_arr +100]
np.select(condlist, choielist, default = temp_arr) #default값 설정하기

array([100, 101,   2,   3,   4,   5,  12,  14,  16,  18])